<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>EmlakOfisi.DAL</RootNamespace>
    <AssemblyName>EmlakOfisi.DAL</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MySql.Data" Version="9.2.0" />
  </ItemGroup>
</Project>
